server:
  port: 9910
#spring配置
spring:
  redis:
    database: 3
    host: 192.168.3.62
    port: 6379

# security
security:
  config:
    captcha-code:
      enable: true
    enableCors: true
    header: Authorization
    # 令牌前缀
    token-start-with: bearer
    # 必须使用最少88位的Base64对该令牌进行编码
    # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
    #  token-validity-in-seconds: 60000
    token-validity-in-seconds: 1800
    #  验证码 key(配置key意味着对验证码进行校验)
    #  使用方式：
    #        配置验证缓存前缀key即为 codeKey
    #        生成验证码并生成唯一值例如 uuid 并且 codeKey+uuid 作为redis key缓存验证码
    #        uuid发送给客户端，客户端提交请求携带验证码以及uuid
    #  code-key: code-key
    # 是否踢掉之前已经登录的token
    single-login: false
    # 匿名访问url
    ignoring-urls:
      - /api/v1
    # token校验访问url
#    auth-urls-prefix:
#      - /api/**
    # 密码加密的私钥, 密码加密传输，前端公钥加密，后端私钥解密
    rsa-private-key: "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKOk5eDYZoeIAg9z4l3ooaJB+vnEhbyyi5DqXeDSiW8rD79SEt42wt8O2zsEbdddRfWPlcn96BJPDFGl6vnA0wPbQcw0fDH86Z4gKrKClVT7RJAHP43Km2oNFMsrL/puxhW1lW15db235KJYKsDyHZmxAs68H0R+pud1d9h7K+aNAgMBAAECgYAFXQ47xFv37TlEEGRG96z0iH0VWp+Xg7KXWVciW0Qt5JdrieEcb2cLsIz27jo7aM82MTKToELO9tBMjMeaz/sag6qbuZQ9jDNanKHxyf2Cpxum460rK0utpr3zShSvuGzwwy9gbfG5sX+y+AU/X3cF8dERPay5cXVO/ZRoQTD4cQJBAPAYH8zbsuaoEZSy8qaqSkwi/+Xi3rv4O6SrYUHLuiwcb0P3dO6Ubs4UnNx0XjGZ+dzerXMCTj+UzftBeGP3eTsCQQCufDgP6gQKOwQ0KUdBiyTUhHu2F7JWwog4T224xM+fEW8hCM165DY3WjcYh0M0EnkdMotElqGbOhc57Tfa/eLXAkAMeWRlk2CXJVJMhIOg7yYPEJ51BjWGVJ5crt7NuVUB57RMNrYnkySyplWECrO+Jf7aX+NpH0yLdyLAlCU6JGhzAkAZ00Do+hYG/Z0tqz5ksReObN1yoic/OCO5UehHhLnGLWppVUg0fDqaDrxA4SRNPL64V5bNXA4nT33IkRfHTfSZAkBcbgo395Bjs7kb3rNMnV8COFC+lq2GxJFU4Pig6WVSANMct6DjmHth50ZpD4C4mrs7s3VJfLjsOEvrgi6InEeZ"
    des-password: 12345678
    app-run-delete-history-token: false
    # 配置加密方式
    id-for-encode: bcrypt
    # 基于 @PreAuthorize 注解权限授权，微信公众号/小程序这里无需权限授权访问的，推荐使用 auth-type: CODE
    # 方法上不添加 @PreAuthorize 权限就不会进行权限授权认证，只认证登录token
    auth-type: SERVICE
    dynamic-refresh-token: true
    service-name: service
    service-handler-method: methodName
##    可选- 如果是api服务层,前端需要传参数：接口方法名称
##    如果设置为true，需要serviceHandlerMethod 指定前端要调用的方法的参数名称
##    这时前端不只是传serviceName 需要调用的服务，还要传 serviceHandlerMethod具体要调用服务下的哪个接口方法
    api-service: true