server:
  port: 9910

spring:
  data:
    redis:
      database: 6
      host: 192.168.1.42
      port: 6379
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:doc/db/osinn.db #jdbc:sqlite::resource:db/osinn.db

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:**/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# security
security:
  config:
    # 建议换成自己的密码
    des-password: 123456789
    expire-time: 14400 # 过期时间默认4小时
    expire-ratio: 0.5 # 过期时间剩余比例，0-1之间，默认 0.5 即时间过半时刷新token缓存过期时间
    # 匿名访问url
    ignoring-urls:
      - /login
#      - /addUser
    # 密码加密的私钥, 密码加密传输，前端公钥加密，后端私钥解密
#    rsa-private-key: "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKOk5eDYZoeIAg9z4l3ooaJB+vnEhbyyi5DqXeDSiW8rD79SEt42wt8O2zsEbdddRfWPlcn96BJPDFGl6vnA0wPbQcw0fDH86Z4gKrKClVT7RJAHP43Km2oNFMsrL/puxhW1lW15db235KJYKsDyHZmxAs68H0R+pud1d9h7K+aNAgMBAAECgYAFXQ47xFv37TlEEGRG96z0iH0VWp+Xg7KXWVciW0Qt5JdrieEcb2cLsIz27jo7aM82MTKToELO9tBMjMeaz/sag6qbuZQ9jDNanKHxyf2Cpxum460rK0utpr3zShSvuGzwwy9gbfG5sX+y+AU/X3cF8dERPay5cXVO/ZRoQTD4cQJBAPAYH8zbsuaoEZSy8qaqSkwi/+Xi3rv4O6SrYUHLuiwcb0P3dO6Ubs4UnNx0XjGZ+dzerXMCTj+UzftBeGP3eTsCQQCufDgP6gQKOwQ0KUdBiyTUhHu2F7JWwog4T224xM+fEW8hCM165DY3WjcYh0M0EnkdMotElqGbOhc57Tfa/eLXAkAMeWRlk2CXJVJMhIOg7yYPEJ51BjWGVJ5crt7NuVUB57RMNrYnkySyplWECrO+Jf7aX+NpH0yLdyLAlCU6JGhzAkAZ00Do+hYG/Z0tqz5ksReObN1yoic/OCO5UehHhLnGLWppVUg0fDqaDrxA4SRNPL64V5bNXA4nT33IkRfHTfSZAkBcbgo395Bjs7kb3rNMnV8COFC+lq2GxJFU4Pig6WVSANMct6DjmHth50ZpD4C4mrs7s3VJfLjsOEvrgi6InEeZ"


#security:
#  config:
#    enableCors: false
#    header: Authorization
#    # 令牌前缀
#    token-start-with: "mbm_"
#    # 必须使用最少88位的Base64对该令牌进行编码
#    # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
#    #  token-validity-in-seconds: 60000
#    #  验证码 key(配置key意味着对验证码进行校验)
#    #  使用方式：
#    #        配置验证缓存前缀key即为 codeKey
#    #        生成验证码并生成唯一值例如 uuid 并且 codeKey+uuid 作为redis key缓存验证码
#    #        uuid发送给客户端，客户端提交请求携带验证码以及uuid
#    #  code-key: code-key
#    # 是否踢掉之前已经登录的token
#    single-login: false
#    # 匿名访问url
#    ignoring-urls:
#      - /login
#    # token校验访问url
##    auth-urls-prefix:
##      - /api/**
#    # 密码加密的私钥, 密码加密传输，前端公钥加密，后端私钥解密
#    rsa-private-key: "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKOk5eDYZoeIAg9z4l3ooaJB+vnEhbyyi5DqXeDSiW8rD79SEt42wt8O2zsEbdddRfWPlcn96BJPDFGl6vnA0wPbQcw0fDH86Z4gKrKClVT7RJAHP43Km2oNFMsrL/puxhW1lW15db235KJYKsDyHZmxAs68H0R+pud1d9h7K+aNAgMBAAECgYAFXQ47xFv37TlEEGRG96z0iH0VWp+Xg7KXWVciW0Qt5JdrieEcb2cLsIz27jo7aM82MTKToELO9tBMjMeaz/sag6qbuZQ9jDNanKHxyf2Cpxum460rK0utpr3zShSvuGzwwy9gbfG5sX+y+AU/X3cF8dERPay5cXVO/ZRoQTD4cQJBAPAYH8zbsuaoEZSy8qaqSkwi/+Xi3rv4O6SrYUHLuiwcb0P3dO6Ubs4UnNx0XjGZ+dzerXMCTj+UzftBeGP3eTsCQQCufDgP6gQKOwQ0KUdBiyTUhHu2F7JWwog4T224xM+fEW8hCM165DY3WjcYh0M0EnkdMotElqGbOhc57Tfa/eLXAkAMeWRlk2CXJVJMhIOg7yYPEJ51BjWGVJ5crt7NuVUB57RMNrYnkySyplWECrO+Jf7aX+NpH0yLdyLAlCU6JGhzAkAZ00Do+hYG/Z0tqz5ksReObN1yoic/OCO5UehHhLnGLWppVUg0fDqaDrxA4SRNPL64V5bNXA4nT33IkRfHTfSZAkBcbgo395Bjs7kb3rNMnV8COFC+lq2GxJFU4Pig6WVSANMct6DjmHth50ZpD4C4mrs7s3VJfLjsOEvrgi6InEeZ"
#    app-run-delete-history-token: false
#    # 配置加密方式
#    id-for-encode: bcrypt
#    # 基于 @PreAuthorize 注解权限授权，微信公众号/小程序这里无需权限授权访问的，推荐使用 auth-type: CODE
#    # 方法上不添加 @PreAuthorize 权限就不会进行权限授权认证，只认证登录token
#    auth-type: code
#    dynamic-refresh-token: true
#    cache-online-user-info-key-prefix: spring_security_auth_example:key_

logging:
  level:
    io.github.osinn: debug
