server:
  port: 9910

spring:
  data:
    redis:
      database: 6
      host: 127.0.0.1
      port: 6379
  datasource:
    #引用项目中的数据库文件
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:doc/db/osinn.db #jdbc:sqlite::resource:db/osinn.db

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:**/mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# security
security:
  config:
    # 建议换成自己的密码
    expire-time: 14400 # 过期时间默认4小时
    expire-ratio: 0.5 # 过期时间剩余比例，0-1之间，默认 0.5 即时间过半时刷新token缓存过期时间
    # 匿名访问url
    ignoring-urls:
      - /login
      - /addUser
    # 如果配置此处密钥，则需要前端公钥加密传输密码
#    rsa-private-key: ""

logging:
  level:
    io.github.osinn: debug
